<?php
# Generated by the php-protobuf-generator.  DO NOT EDIT!
# source: tests/imported.proto

namespace Gary;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * .gary.Imported message
 */
class Imported extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf <code>int32 field1 = 1;</code>
     */
    private $field1;
    
    public function __construct()
    {
        \GPBMetadata\Tests\Imported::initOnce();
        parent::__construct();
    }
    
    /**
     * Generated from protobuf <code>int32 field1 = 1;</code>
     * @param integer $value
     * @return $this
     */
    public function setField1($value)
    {
        GPBUtil::checkInt32($value);
        $this->field1 = $value;
        return $this;
    }
    
    /**
     * Generated from protobuf <code>int32 field1 = 1;</code>
     * @return integer
     */
    public function getField1()
    {
        return $this->field1;
    }
    
}
