<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tests/test3.proto

namespace Gary\Test;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gary.test.Bar</code>
 */
class Bar extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double double_field = 1;</code>
     */
    private $double_field = 0.0;

    public function __construct() {
        \GPBMetadata\Tests\Test3::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>double double_field = 1;</code>
     * @return float
     */
    public function getDoubleField()
    {
        return $this->double_field;
    }

    /**
     * Generated from protobuf field <code>double double_field = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setDoubleField($var)
    {
        GPBUtil::checkDouble($var);
        $this->double_field = $var;

        return $this;
    }

}

