<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tests/test3.proto

namespace Gary\Test;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * message comment??
 *
 * Generated from protobuf message <code>gary.test.Foo</code>
 */
class Foo extends \Google\Protobuf\Internal\Message
{
    /**
     * field comment??
     *
     * Generated from protobuf field <code>double double_field = 1;</code>
     */
    private $double_field = 0.0;
    /**
     * Generated from protobuf field <code>float float_field = 2;</code>
     */
    private $float_field = 0.0;
    /**
     * Generated from protobuf field <code>int32 int32_field = 3;</code>
     */
    private $int32_field = 0;
    /**
     * Generated from protobuf field <code>int64 int64_field = 4;</code>
     */
    private $int64_field = 0;
    /**
     * Generated from protobuf field <code>uint32 uint32_field = 5;</code>
     */
    private $uint32_field = 0;
    /**
     * Generated from protobuf field <code>uint64 uint64_field = 6;</code>
     */
    private $uint64_field = 0;
    /**
     * Generated from protobuf field <code>sint32 sint32_field = 7;</code>
     */
    private $sint32_field = 0;
    /**
     * Generated from protobuf field <code>sint64 sint64_field = 8;</code>
     */
    private $sint64_field = 0;
    /**
     * Generated from protobuf field <code>fixed32 fixed32_field = 9;</code>
     */
    private $fixed32_field = 0;
    /**
     * Generated from protobuf field <code>fixed64 fixed64_field = 10;</code>
     */
    private $fixed64_field = 0;
    /**
     * Generated from protobuf field <code>sfixed32 sfixed32_field = 11;</code>
     */
    private $sfixed32_field = 0;
    /**
     * Generated from protobuf field <code>sfixed64 sfixed64_field = 12;</code>
     */
    private $sfixed64_field = 0;
    /**
     * Generated from protobuf field <code>bool bool_field = 13;</code>
     */
    private $bool_field = false;
    /**
     * Generated from protobuf field <code>string string_field = 14;</code>
     */
    private $string_field = '';
    /**
     * Generated from protobuf field <code>bytes bytes_field = 15;</code>
     */
    private $bytes_field = '';
    /**
     * Generated from protobuf field <code>repeated int32 repeated_field = 16;</code>
     */
    private $repeated_field;
    /**
     * Generated from protobuf field <code>.gary.test.Bar embedded_field = 17;</code>
     */
    private $embedded_field = null;
    /**
     * Generated from protobuf field <code>repeated double double_packed_field = 18 [packed = true];</code>
     */
    private $double_packed_field;
    /**
     * Generated from protobuf field <code>repeated float float_packed_field = 19 [packed = true];</code>
     */
    private $float_packed_field;
    /**
     * Generated from protobuf field <code>repeated fixed32 fixed32_packed_field = 20 [packed = true];</code>
     */
    private $fixed32_packed_field;
    /**
     * Generated from protobuf field <code>repeated fixed64 fixed64_packed_field = 21 [packed = true];</code>
     */
    private $fixed64_packed_field;
    /**
     * Generated from protobuf field <code>repeated int32 int32_packed_field = 22 [packed = true];</code>
     */
    private $int32_packed_field;
    /**
     * Generated from protobuf field <code>repeated sint32 sint32_packed_field = 23 [packed = true];</code>
     */
    private $sint32_packed_field;
    /**
     * Generated from protobuf field <code>repeated bool bool_packed_field = 24 [packed = true];</code>
     */
    private $bool_packed_field;
    /**
     * Generated from protobuf field <code>.gary.test.Baz optional_embedded_field = 25;</code>
     */
    private $optional_embedded_field = null;
    /**
     * Generated from protobuf field <code>repeated .gary.test.Bar repeated_obj_field = 26;</code>
     */
    private $repeated_obj_field;
    /**
     * Generated from protobuf field <code>repeated string repeated_string_field = 27;</code>
     */
    private $repeated_string_field;
    /**
     * Generated from protobuf field <code>map<int32, .gary.test.Foo.Embedded> map_field = 28;</code>
     */
    private $map_field;
    /**
     * Generated from protobuf field <code>.gary.Imported imported_field = 29;</code>
     */
    private $imported_field = null;

    public function __construct() {
        \GPBMetadata\Tests\Test3::initOnce();
        parent::__construct();
    }

    /**
     * field comment??
     *
     * Generated from protobuf field <code>double double_field = 1;</code>
     * @return float
     */
    public function getDoubleField()
    {
        return $this->double_field;
    }

    /**
     * field comment??
     *
     * Generated from protobuf field <code>double double_field = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setDoubleField($var)
    {
        GPBUtil::checkDouble($var);
        $this->double_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float float_field = 2;</code>
     * @return float
     */
    public function getFloatField()
    {
        return $this->float_field;
    }

    /**
     * Generated from protobuf field <code>float float_field = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setFloatField($var)
    {
        GPBUtil::checkFloat($var);
        $this->float_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 int32_field = 3;</code>
     * @return int
     */
    public function getInt32Field()
    {
        return $this->int32_field;
    }

    /**
     * Generated from protobuf field <code>int32 int32_field = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setInt32Field($var)
    {
        GPBUtil::checkInt32($var);
        $this->int32_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 int64_field = 4;</code>
     * @return int|string
     */
    public function getInt64Field()
    {
        return $this->int64_field;
    }

    /**
     * Generated from protobuf field <code>int64 int64_field = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setInt64Field($var)
    {
        GPBUtil::checkInt64($var);
        $this->int64_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 uint32_field = 5;</code>
     * @return int
     */
    public function getUint32Field()
    {
        return $this->uint32_field;
    }

    /**
     * Generated from protobuf field <code>uint32 uint32_field = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setUint32Field($var)
    {
        GPBUtil::checkUint32($var);
        $this->uint32_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 uint64_field = 6;</code>
     * @return int|string
     */
    public function getUint64Field()
    {
        return $this->uint64_field;
    }

    /**
     * Generated from protobuf field <code>uint64 uint64_field = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUint64Field($var)
    {
        GPBUtil::checkUint64($var);
        $this->uint64_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint32 sint32_field = 7;</code>
     * @return int
     */
    public function getSint32Field()
    {
        return $this->sint32_field;
    }

    /**
     * Generated from protobuf field <code>sint32 sint32_field = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setSint32Field($var)
    {
        GPBUtil::checkInt32($var);
        $this->sint32_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint64 sint64_field = 8;</code>
     * @return int|string
     */
    public function getSint64Field()
    {
        return $this->sint64_field;
    }

    /**
     * Generated from protobuf field <code>sint64 sint64_field = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSint64Field($var)
    {
        GPBUtil::checkInt64($var);
        $this->sint64_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 fixed32_field = 9;</code>
     * @return int
     */
    public function getFixed32Field()
    {
        return $this->fixed32_field;
    }

    /**
     * Generated from protobuf field <code>fixed32 fixed32_field = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setFixed32Field($var)
    {
        GPBUtil::checkUint32($var);
        $this->fixed32_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed64 fixed64_field = 10;</code>
     * @return int|string
     */
    public function getFixed64Field()
    {
        return $this->fixed64_field;
    }

    /**
     * Generated from protobuf field <code>fixed64 fixed64_field = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFixed64Field($var)
    {
        GPBUtil::checkUint64($var);
        $this->fixed64_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sfixed32 sfixed32_field = 11;</code>
     * @return int
     */
    public function getSfixed32Field()
    {
        return $this->sfixed32_field;
    }

    /**
     * Generated from protobuf field <code>sfixed32 sfixed32_field = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setSfixed32Field($var)
    {
        GPBUtil::checkInt32($var);
        $this->sfixed32_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sfixed64 sfixed64_field = 12;</code>
     * @return int|string
     */
    public function getSfixed64Field()
    {
        return $this->sfixed64_field;
    }

    /**
     * Generated from protobuf field <code>sfixed64 sfixed64_field = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSfixed64Field($var)
    {
        GPBUtil::checkInt64($var);
        $this->sfixed64_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool bool_field = 13;</code>
     * @return bool
     */
    public function getBoolField()
    {
        return $this->bool_field;
    }

    /**
     * Generated from protobuf field <code>bool bool_field = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setBoolField($var)
    {
        GPBUtil::checkBool($var);
        $this->bool_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string string_field = 14;</code>
     * @return string
     */
    public function getStringField()
    {
        return $this->string_field;
    }

    /**
     * Generated from protobuf field <code>string string_field = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setStringField($var)
    {
        GPBUtil::checkString($var, True);
        $this->string_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes bytes_field = 15;</code>
     * @return string
     */
    public function getBytesField()
    {
        return $this->bytes_field;
    }

    /**
     * Generated from protobuf field <code>bytes bytes_field = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setBytesField($var)
    {
        GPBUtil::checkString($var, False);
        $this->bytes_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 repeated_field = 16;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRepeatedField()
    {
        return $this->repeated_field;
    }

    /**
     * Generated from protobuf field <code>repeated int32 repeated_field = 16;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRepeatedField($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->repeated_field = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.gary.test.Bar embedded_field = 17;</code>
     * @return \Gary\Test\Bar
     */
    public function getEmbeddedField()
    {
        return $this->embedded_field;
    }

    /**
     * Generated from protobuf field <code>.gary.test.Bar embedded_field = 17;</code>
     * @param \Gary\Test\Bar $var
     * @return $this
     */
    public function setEmbeddedField($var)
    {
        GPBUtil::checkMessage($var, \Gary\Test\Bar::class);
        $this->embedded_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated double double_packed_field = 18 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDoublePackedField()
    {
        return $this->double_packed_field;
    }

    /**
     * Generated from protobuf field <code>repeated double double_packed_field = 18 [packed = true];</code>
     * @param float[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDoublePackedField($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::DOUBLE);
        $this->double_packed_field = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated float float_packed_field = 19 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFloatPackedField()
    {
        return $this->float_packed_field;
    }

    /**
     * Generated from protobuf field <code>repeated float float_packed_field = 19 [packed = true];</code>
     * @param float[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFloatPackedField($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->float_packed_field = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated fixed32 fixed32_packed_field = 20 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFixed32PackedField()
    {
        return $this->fixed32_packed_field;
    }

    /**
     * Generated from protobuf field <code>repeated fixed32 fixed32_packed_field = 20 [packed = true];</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFixed32PackedField($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FIXED32);
        $this->fixed32_packed_field = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated fixed64 fixed64_packed_field = 21 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFixed64PackedField()
    {
        return $this->fixed64_packed_field;
    }

    /**
     * Generated from protobuf field <code>repeated fixed64 fixed64_packed_field = 21 [packed = true];</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFixed64PackedField($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FIXED64);
        $this->fixed64_packed_field = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 int32_packed_field = 22 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInt32PackedField()
    {
        return $this->int32_packed_field;
    }

    /**
     * Generated from protobuf field <code>repeated int32 int32_packed_field = 22 [packed = true];</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInt32PackedField($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->int32_packed_field = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated sint32 sint32_packed_field = 23 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSint32PackedField()
    {
        return $this->sint32_packed_field;
    }

    /**
     * Generated from protobuf field <code>repeated sint32 sint32_packed_field = 23 [packed = true];</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSint32PackedField($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::SINT32);
        $this->sint32_packed_field = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bool bool_packed_field = 24 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBoolPackedField()
    {
        return $this->bool_packed_field;
    }

    /**
     * Generated from protobuf field <code>repeated bool bool_packed_field = 24 [packed = true];</code>
     * @param bool[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBoolPackedField($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BOOL);
        $this->bool_packed_field = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.gary.test.Baz optional_embedded_field = 25;</code>
     * @return \Gary\Test\Baz
     */
    public function getOptionalEmbeddedField()
    {
        return $this->optional_embedded_field;
    }

    /**
     * Generated from protobuf field <code>.gary.test.Baz optional_embedded_field = 25;</code>
     * @param \Gary\Test\Baz $var
     * @return $this
     */
    public function setOptionalEmbeddedField($var)
    {
        GPBUtil::checkMessage($var, \Gary\Test\Baz::class);
        $this->optional_embedded_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .gary.test.Bar repeated_obj_field = 26;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRepeatedObjField()
    {
        return $this->repeated_obj_field;
    }

    /**
     * Generated from protobuf field <code>repeated .gary.test.Bar repeated_obj_field = 26;</code>
     * @param \Gary\Test\Bar[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRepeatedObjField($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Gary\Test\Bar::class);
        $this->repeated_obj_field = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string repeated_string_field = 27;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRepeatedStringField()
    {
        return $this->repeated_string_field;
    }

    /**
     * Generated from protobuf field <code>repeated string repeated_string_field = 27;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRepeatedStringField($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->repeated_string_field = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<int32, .gary.test.Foo.Embedded> map_field = 28;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMapField()
    {
        return $this->map_field;
    }

    /**
     * Generated from protobuf field <code>map<int32, .gary.test.Foo.Embedded> map_field = 28;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMapField($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::MESSAGE, \Gary\Test\Foo_Embedded::class);
        $this->map_field = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.gary.Imported imported_field = 29;</code>
     * @return \Gary\Imported
     */
    public function getImportedField()
    {
        return $this->imported_field;
    }

    /**
     * Generated from protobuf field <code>.gary.Imported imported_field = 29;</code>
     * @param \Gary\Imported $var
     * @return $this
     */
    public function setImportedField($var)
    {
        GPBUtil::checkMessage($var, \Gary\Imported::class);
        $this->imported_field = $var;

        return $this;
    }

}

