<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tests/test3.proto

namespace Gary\Test;

/**
 * Protobuf enum <code>Gary\Test\Foo\Enum</code>
 */
class Foo_Enum
{
    /**
     * enum comment
     *
     * Generated from protobuf enum <code>EnumOne = 0;</code>
     */
    const EnumOne = 0;
}

