<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tests/test3.proto

namespace Gary\Test;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gary.test.Foo.Embedded.Deep</code>
 */
class Foo_Embedded_Deep extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 f1 = 1;</code>
     */
    private $f1 = 0;

    public function __construct() {
        \GPBMetadata\Tests\Test3::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 f1 = 1;</code>
     * @return int
     */
    public function getF1()
    {
        return $this->f1;
    }

    /**
     * Generated from protobuf field <code>int32 f1 = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setF1($var)
    {
        GPBUtil::checkInt32($var);
        $this->f1 = $var;

        return $this;
    }

}

