<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tests/test3.proto

namespace Gary\Test;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gary.test.GetByIdsRequest</code>
 */
class GetByIdsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * input
     *
     * Generated from protobuf field <code>repeated int32 ids = 1;</code>
     */
    private $ids;

    public function __construct() {
        \GPBMetadata\Tests\Test3::initOnce();
        parent::__construct();
    }

    /**
     * input
     *
     * Generated from protobuf field <code>repeated int32 ids = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIds()
    {
        return $this->ids;
    }

    /**
     * input
     *
     * Generated from protobuf field <code>repeated int32 ids = 1;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->ids = $arr;

        return $this;
    }

}

