<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tests/test3.proto

namespace Gary\Test;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gary.test.GetByIdsResponse</code>
 */
class GetByIdsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 code = 1;</code>
     */
    private $code = 0;
    /**
     * Generated from protobuf field <code>string msg = 2;</code>
     */
    private $msg = '';
    /**
     * data
     *
     * Generated from protobuf field <code>map<int32, .gary.test.GetByIdsResponse.Info> data = 3;</code>
     */
    private $data;

    public function __construct() {
        \GPBMetadata\Tests\Test3::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msg = 2;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     * Generated from protobuf field <code>string msg = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg = $var;

        return $this;
    }

    /**
     * data
     *
     * Generated from protobuf field <code>map<int32, .gary.test.GetByIdsResponse.Info> data = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * data
     *
     * Generated from protobuf field <code>map<int32, .gary.test.GetByIdsResponse.Info> data = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::MESSAGE, \Gary\Test\GetByIdsResponse_Info::class);
        $this->data = $arr;

        return $this;
    }

}

