<?php
# Generated by the php-protobuf-generator.  DO NOT EDIT!
# source: tests/imported.proto

namespace GPBMetadata\Tests;

class Imported
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a480a1474657374732f696d706f727465642e70726f746f120467617279" . 
            "22220a08496d706f7274656412160a066669656c64311801200128055206" . 
            "6669656c6431620670726f746f33"
        ));
        static::$is_initialized = true;
    }
}
