<?php
# Generated by the php-protobuf-generator.  DO NOT EDIT!
# source: tests/test3.proto

namespace Gary\Test;

/**
 * Gary\Test\Foo_Enum enum embedded in .gary.test.Foo message
 */
final class Foo_Enum
{
    const EnumOne = 0;
    
    /**
     * Returns defined enum values
     *
     * @return int[]
     */
    public function getEnumValues()
    {
        return array(
            'EnumOne' => self::EnumOne,
        );
    }
}
